### ISSUE TITLE
Button width/left does not reflect padding size

### ISSUE THREAD

**Issue by whoozle** [pureqml/controls#12]
this renders buttons misaligned to vertical center if horizontalCenter/centerIn anchors used.

probably relevant to 
```box-sizing: content-box; ```

![image](https://user-images.githubusercontent.com/480115/56591143-1d4a5080-65e0-11e9-84ff-ac35e664c001.png)

**Comment by comrat** [comment]
Fixed
99302feb5a63a4dccb7ac3eb274eb0a674429f89
