### ISSUE TITLE
Code syntax highlighter

### ISSUE THREAD

**Issue by vadi2** [pureqml/controls#13]
Can the code syntax highlighter be used with Qt Quick's TextField? If no, can it be used on the desktop in another widget?

**Comment by whoozle** [comment]
Hello, @vadi2 
Our qml dialect is not really compatible with Qt Quick. Some things are, but generally you can't write code that runs on both platforms. We use `CodeHighlighter` component for the fancy code snippets on our website.
If that does not answer your question, please elaborate.
Thanks

**Comment by vadi2** [comment]
It does, thanks!
